"""
Formal QuantBoy target-weight strategies.
"""

from .etf_equal_weight import EqualWeightStrategy
from .etf_momentum import MomentumRotationStrategy
from .basic import (
    AbsoluteMomentumStrategy,
    AcceleratingMomentumStrategy,
    BreakoutMomentumStrategy,
    CalendarFilteredStatefulAcceleratingEnsembleStrategy,
    CompositeMomentumStrategy,
    DateWindowFilteredStatefulAcceleratingEnsembleStrategy,
    DrawdownAdjustedMomentumStrategy,
    DrawdownControlStrategy,
    DualMovingAverageStrategy,
    DualMomentumStrategy,
    LowVolatilityStrategy,
    LowVolatilityTrendStrategy,
    MaxSharpeStrategy,
    MeanReversionStrategy,
    MinVarianceStrategy,
    MomentumRiskParityStrategy,
    MovingAverageTrendStrategy,
    RiskAdjustedMomentumStrategy,
    RiskParityStrategy,
    ScheduledRotationStrategy,
    SmoothedMomentumStrategy,
    StatefulAcceleratingEnsembleStrategy,
    StatefulAcceleratingMomentumStrategy,
    TrailingSharpeMomentumStrategy,
    TrendFilteredMomentumStrategy,
    TrendRiskParityStrategy,
    TrendTimingStrategy,
    VolatilityTargetStrategy,
)
from .bundle_multifactor import (
    BundleMultiFactorMomentumStrategy,
    StatefulBundleMultiFactorMomentumStrategy,
)
from .wrappers import MarketTrendFilterStrategy, WeightedStrategyEnsemble

__all__ = [
    "EqualWeightStrategy",
    "MomentumRotationStrategy",
    "MovingAverageTrendStrategy",
    "DualMovingAverageStrategy",
    "MeanReversionStrategy",
    "LowVolatilityStrategy",
    "RiskParityStrategy",
    "TrendTimingStrategy",
    "AbsoluteMomentumStrategy",
    "AcceleratingMomentumStrategy",
    "CalendarFilteredStatefulAcceleratingEnsembleStrategy",
    "DateWindowFilteredStatefulAcceleratingEnsembleStrategy",
    "DualMomentumStrategy",
    "VolatilityTargetStrategy",
    "DrawdownControlStrategy",
    "TrendRiskParityStrategy",
    "MinVarianceStrategy",
    "MaxSharpeStrategy",
    "LowVolatilityTrendStrategy",
    "RiskAdjustedMomentumStrategy",
    "ScheduledRotationStrategy",
    "DrawdownAdjustedMomentumStrategy",
    "TrailingSharpeMomentumStrategy",
    "SmoothedMomentumStrategy",
    "StatefulAcceleratingEnsembleStrategy",
    "StatefulAcceleratingMomentumStrategy",
    "TrendFilteredMomentumStrategy",
    "MomentumRiskParityStrategy",
    "CompositeMomentumStrategy",
    "BreakoutMomentumStrategy",
    "BundleMultiFactorMomentumStrategy",
    "StatefulBundleMultiFactorMomentumStrategy",
    "MarketTrendFilterStrategy",
    "WeightedStrategyEnsemble",
]
